ARG BASE_IMAGE=byconity_base:latest
FROM ${BASE_IMAGE}

RUN yum groupinstall "GNOME Desktop" -y && \
  systemctl set-default graphical.target && \
  yum install tigervnc-server -y \

COPY  vncserver.service  /etc/systemd/system/vncserver.service

COPY dev.sh /

CMD ["/bin/bash", "/dev.sh"]