FROM centos:centos7

USER root

COPY $RPM_DIR/$RPM_NAME /${RPM_NAME}

RUN rpm -ivh --nodeps /${RPM_NAME} && \
    rm -rf /${RPM_NAME} && \
    systemctl daemon-reload
# && systemctl enable byconity-server.service