ARG BASE_IMAGE=byconity_base:latest
FROM ${BASE_IMAGE}

RUN yum groupinstall "GNOME Desktop" -y && \
  systemctl set-default graphical.target && \
  yum install tigervnc-server -y \

COPY  ../../vncserver.service  /etc/systemd/system/vncserver.service

RUN  systemctl daemon-reload && \
  systemctl enable vncserver.service

#vncpasswd
#firewall-cmd --permanent --add-port=5901/tcp
#firewall-cmd --reload
#firewall-cmd --permanent --add-service vnc-server
#systemctl restart firewalld.service
#netstat -lnpt|grep Xvnc